server:
  port: 8080

spring:
  application:
    name: orbis-gateway

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        register: true

    gateway:
      routes:
        - id: event-service
          uri: http://localhost:8081
          predicates:
            - Path=/events/**

        - id: ticket-service
          uri: http://localhost:8082
          predicates:
            - Path=/tickets/**

      discovery:
        locator:
          enabled: true